import { TableNode, RelationshipEdge } from "@/types/schema"

export function generateDrizzle(nodes: TableNode[], edges: RelationshipEdge[]): string {
  if (nodes.length === 0) return "// No tables to generate"

  let code = `// Generated by SchemaLab\n// Language: Drizzle ORM (PostgreSQL)\n\n`
  code += `import { pgTable, serial, integer, varchar, boolean, timestamp, doublePrecision, text, uuid, jsonb } from "drizzle-orm/pg-core";\nimport { relations } from "drizzle-orm";\n\n`

  // Generate table definitions
  for (const node of nodes) {
    const { tableName, fields } = node.data
    const varName = toCamelCase(tableName)

    code += `export const ${varName} = pgTable("${tableName}", {\n`

    for (const field of fields) {
      const isPK = field.constraints.includes("PRIMARY_KEY")
      const isAI = field.constraints.includes("AUTO_INCREMENT")
      const isNN = field.constraints.includes("NOT_NULL")
      const isUQ = field.constraints.includes("UNIQUE")

      const col = `  ${field.name}: ${mapDrizzleColumn(field.type, field.name, isPK && isAI)}`

      const modifiers: string[] = []
      if (isPK) modifiers.push(".primaryKey()")
      if (isNN && !isPK) modifiers.push(".notNull()")
      if (isUQ) modifiers.push(".unique()")
      if (field.constraints.includes("DEFAULT") && field.defaultValue) {
        modifiers.push(`.default(${field.defaultValue})`)
      }

      code += col + modifiers.join("") + ",\n"
    }

    code += `});\n\n`
  }

  // Generate relations
  for (const node of nodes) {
    const { tableName } = node.data
    const varName = toCamelCase(tableName)
    const outgoing = edges.filter((e) => e.source === node.id)
    const incoming = edges.filter((e) => e.target === node.id)

    if (outgoing.length === 0 && incoming.length === 0) continue

    code += `export const ${varName}Relations = relations(${varName}, ({ one, many }) => ({\n`

    for (const edge of outgoing) {
      const targetNode = nodes.find((n) => n.id === edge.target)
      if (targetNode) {
        const targetVar = toCamelCase(targetNode.data.tableName)
        code += `  ${targetNode.data.tableName}: one(${targetVar}, {\n`
        code += `    fields: [${varName}.${edge.data.sourceField}],\n`
        code += `    references: [${targetVar}.${edge.data.targetField}],\n`
        code += `  }),\n`
      }
    }

    for (const edge of incoming) {
      const sourceNode = nodes.find((n) => n.id === edge.source)
      if (sourceNode) {
        const sourceVar = toCamelCase(sourceNode.data.tableName)
        if (edge.data.relationshipType === "ONE_TO_MANY" || edge.data.relationshipType === "MANY_TO_MANY") {
          code += `  ${sourceNode.data.tableName}s: many(${sourceVar}),\n`
        } else {
          code += `  ${sourceNode.data.tableName}: one(${sourceVar}),\n`
        }
      }
    }

    code += `}));\n\n`
  }

  return code.trim()
}

function toCamelCase(str: string): string {
  const parts = str.split(/[_\s-]+/)
  return parts[0].toLowerCase() + parts.slice(1).map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join("")
}

function mapDrizzleColumn(type: string, name: string, isSerial: boolean): string {
  if (isSerial) return `serial("${name}")`
  const map: Record<string, string> = {
    Int: `integer("${name}")`,
    String: `varchar("${name}", { length: 255 })`,
    Boolean: `boolean("${name}")`,
    DateTime: `timestamp("${name}", { withTimezone: true })`,
    Float: `doublePrecision("${name}")`,
    UUID: `uuid("${name}")`,
    Text: `text("${name}")`,
    JSON: `jsonb("${name}")`,
  }
  return map[type] || `text("${name}")`
}
