import { TableNode, RelationshipEdge } from "@/types/schema"

export function generateMongoose(nodes: TableNode[], edges: RelationshipEdge[]): string {
  if (nodes.length === 0) return "// No tables to generate"

  let code = `// Generated by SchemaLab\n// Language: Mongoose\n\n`
  code += `const mongoose = require("mongoose");\n\n`

  for (const node of nodes) {
    const { tableName, fields } = node.data
    const modelName = toPascalCase(tableName)
    const schemaVarName = `${toCamelCase(tableName)}Schema`

    code += `const ${schemaVarName} = new mongoose.Schema({\n`

    for (const field of fields) {
      if (field.constraints.includes("PRIMARY_KEY") && field.name === "id") {
        continue // Mongoose auto-generates _id
      }

      const mongoType = mapMongooseType(field.type)
      const options: string[] = [`type: ${mongoType}`]

      if (field.constraints.includes("NOT_NULL")) {
        options.push("required: true")
      }
      if (field.constraints.includes("UNIQUE")) {
        options.push("unique: true")
      }
      if (field.constraints.includes("DEFAULT") && field.defaultValue) {
        options.push(`default: ${field.defaultValue}`)
      }
      if (field.type === "DateTime" && field.name.toLowerCase().includes("createdat")) {
        options.push("default: Date.now")
      }

      // Check for FK — add ObjectId ref
      const fkEdge = edges.find(
        (e) => e.source === node.id && e.data.sourceField === field.name
      )
      if (fkEdge) {
        const targetNode = nodes.find((n) => n.id === fkEdge.target)
        if (targetNode) {
          code += `  ${field.name}: { type: mongoose.Schema.Types.ObjectId, ref: "${toPascalCase(targetNode.data.tableName)}" },\n`
          continue
        }
      }

      if (options.length === 1) {
        code += `  ${field.name}: ${mongoType},\n`
      } else {
        code += `  ${field.name}: { ${options.join(", ")} },\n`
      }
    }

    code += `}, { timestamps: true });\n\n`
    code += `const ${modelName} = mongoose.model("${modelName}", ${schemaVarName});\n\n`
  }

  code += `module.exports = { ${nodes.map((n) => toPascalCase(n.data.tableName)).join(", ")} };\n`

  return code.trim()
}

function toPascalCase(str: string): string {
  return str
    .split(/[_\s-]+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join("")
}

function toCamelCase(str: string): string {
  const parts = str.split(/[_\s-]+/)
  return parts[0].toLowerCase() + parts.slice(1).map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join("")
}

function mapMongooseType(type: string): string {
  const map: Record<string, string> = {
    Int: "Number",
    String: "String",
    Boolean: "Boolean",
    DateTime: "Date",
    Float: "Number",
    UUID: "String",
    Text: "String",
    JSON: "mongoose.Schema.Types.Mixed",
  }
  return map[type] || "String"
}
