import { TableNode, RelationshipEdge } from "@/types/schema"

export function generatePostgres(nodes: TableNode[], edges: RelationshipEdge[]): string {
  if (nodes.length === 0) return "-- No tables to generate"

  let sql = "-- Generated by SchemaLab\n-- Language: PostgreSQL\n\n"

  for (const node of nodes) {
    const { tableName, fields } = node.data
    sql += `CREATE TABLE "${tableName}" (\n`

    const fieldLines: string[] = []
    for (const field of fields) {
      const isPK = field.constraints.includes("PRIMARY_KEY")
      const isAI = field.constraints.includes("AUTO_INCREMENT")
      const pgType = mapPostgresType(field.type, isPK && isAI)

      let line = `  "${field.name}" ${pgType}`

      if (isPK && !isAI) {
        line += " PRIMARY KEY"
      }
      if (field.constraints.includes("NOT_NULL") && !isPK) {
        line += " NOT NULL"
      }
      if (field.constraints.includes("UNIQUE") && !isPK) {
        line += " UNIQUE"
      }
      if (field.constraints.includes("DEFAULT") && field.defaultValue) {
        line += ` DEFAULT ${field.defaultValue}`
      }

      fieldLines.push(line)
    }

    // Foreign key constraints
    for (const edge of edges) {
      if (edge.source === node.id) {
        const targetNode = nodes.find((n) => n.id === edge.target)
        if (targetNode) {
          fieldLines.push(
            `  CONSTRAINT "fk_${tableName}_${edge.data.sourceField}" FOREIGN KEY ("${edge.data.sourceField}") REFERENCES "${targetNode.data.tableName}"("${edge.data.targetField}") ON DELETE CASCADE`
          )
        }
      }
    }

    sql += fieldLines.join(",\n") + "\n);\n\n"
  }

  // Create indexes for foreign keys
  for (const edge of edges) {
    const sourceNode = nodes.find((n) => n.id === edge.source)
    if (sourceNode) {
      sql += `CREATE INDEX "idx_${sourceNode.data.tableName}_${edge.data.sourceField}" ON "${sourceNode.data.tableName}"("${edge.data.sourceField}");\n`
    }
  }

  return sql.trim()
}

function mapPostgresType(type: string, isSerial: boolean): string {
  if (isSerial) return "SERIAL PRIMARY KEY"
  const map: Record<string, string> = {
    Int: "INTEGER",
    String: "VARCHAR(255)",
    Boolean: "BOOLEAN",
    DateTime: "TIMESTAMPTZ",
    Float: "DOUBLE PRECISION",
    UUID: "UUID",
    Text: "TEXT",
    JSON: "JSONB",
  }
  return map[type] || "TEXT"
}
