import { TableNode, RelationshipEdge } from "@/types/schema"

export function generatePrisma(nodes: TableNode[], edges: RelationshipEdge[]): string {
  if (nodes.length === 0) return "// No tables to generate"

  let prisma = `// Generated by SchemaLab\n// Language: Prisma\n\ngenerator client {\n  provider = "prisma-client-js"\n}\n\ndatasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}\n\n`

  for (const node of nodes) {
    const { tableName, fields } = node.data
    const modelName = toPascalCase(tableName)
    prisma += `model ${modelName} {\n`

    for (const field of fields) {
      let line = `  ${field.name} ${mapPrismaType(field.type)}`

      if (field.constraints.includes("PRIMARY_KEY")) {
        line += " @id"
        if (field.constraints.includes("AUTO_INCREMENT")) {
          line += " @default(autoincrement())"
        }
      }
      if (field.constraints.includes("UNIQUE")) {
        line += " @unique"
      }
      if (field.type === "DateTime" && field.name.toLowerCase().includes("createdat")) {
        line += " @default(now())"
      }
      if (field.type === "UUID" && field.constraints.includes("PRIMARY_KEY")) {
        line = `  ${field.name} String @id @default(uuid())`
      }
      if (field.constraints.includes("DEFAULT") && field.defaultValue) {
        line += ` @default(${field.defaultValue})`
      }

      prisma += line + "\n"
    }

    // Add relation fields
    const outgoingEdges = edges.filter((e) => e.source === node.id)
    const incomingEdges = edges.filter((e) => e.target === node.id)

    for (const edge of outgoingEdges) {
      const targetNode = nodes.find((n) => n.id === edge.target)
      if (targetNode) {
        const targetModelName = toPascalCase(targetNode.data.tableName)
        const relationFieldName = targetNode.data.tableName.toLowerCase()

        if (edge.data.relationshipType === "MANY_TO_MANY") {
          prisma += `  ${relationFieldName}s ${targetModelName}[]\n`
        } else {
          prisma += `  ${relationFieldName} ${targetModelName} @relation(fields: [${edge.data.sourceField}], references: [${edge.data.targetField}])\n`
        }
      }
    }

    for (const edge of incomingEdges) {
      const sourceNode = nodes.find((n) => n.id === edge.source)
      if (sourceNode) {
        const sourceModelName = toPascalCase(sourceNode.data.tableName)
        const relationFieldName = sourceNode.data.tableName.toLowerCase()

        if (edge.data.relationshipType === "ONE_TO_MANY") {
          prisma += `  ${relationFieldName}s ${sourceModelName}[]\n`
        } else if (edge.data.relationshipType === "ONE_TO_ONE") {
          prisma += `  ${relationFieldName} ${sourceModelName}?\n`
        }
      }
    }

    prisma += `}\n\n`
  }

  return prisma.trim()
}

function toPascalCase(str: string): string {
  return str
    .split(/[_\s-]+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join("")
}

function mapPrismaType(type: string): string {
  const map: Record<string, string> = {
    Int: "Int",
    String: "String",
    Boolean: "Boolean",
    DateTime: "DateTime",
    Float: "Float",
    UUID: "String",
    Text: "String",
    JSON: "Json",
  }
  return map[type] || "String"
}
