import { TableNode, RelationshipEdge } from "@/types/schema"

export function generateSQL(nodes: TableNode[], edges: RelationshipEdge[]): string {
  if (nodes.length === 0) return "-- No tables to generate"

  let sql = "-- Generated by SchemaLab\n-- Language: SQL\n\n"

  for (const node of nodes) {
    const { tableName, fields } = node.data
    sql += `CREATE TABLE ${tableName} (\n`

    const fieldLines: string[] = []
    for (const field of fields) {
      let line = `  ${field.name} ${mapSQLType(field.type)}`

      if (field.constraints.includes("PRIMARY_KEY")) {
        line += " PRIMARY KEY"
      }
      if (field.constraints.includes("AUTO_INCREMENT")) {
        line += " AUTOINCREMENT"
      }
      if (field.constraints.includes("NOT_NULL")) {
        line += " NOT NULL"
      }
      if (field.constraints.includes("UNIQUE")) {
        line += " UNIQUE"
      }
      if (field.constraints.includes("DEFAULT") && field.defaultValue) {
        line += ` DEFAULT ${field.defaultValue}`
      }

      fieldLines.push(line)
    }

    // Add foreign key constraints
    for (const edge of edges) {
      if (edge.source === node.id) {
        const targetNode = nodes.find((n) => n.id === edge.target)
        if (targetNode) {
          fieldLines.push(
            `  FOREIGN KEY (${edge.data.sourceField}) REFERENCES ${targetNode.data.tableName}(${edge.data.targetField})`
          )
        }
      }
    }

    sql += fieldLines.join(",\n") + "\n);\n\n"
  }

  return sql.trim()
}

function mapSQLType(type: string): string {
  const map: Record<string, string> = {
    Int: "INTEGER",
    String: "VARCHAR(255)",
    Boolean: "BOOLEAN",
    DateTime: "DATETIME",
    Float: "REAL",
    UUID: "VARCHAR(36)",
    Text: "TEXT",
    JSON: "TEXT",
  }
  return map[type] || "TEXT"
}
