-- Generated by SchemaLab: Initial Complete Migration

-- Create projects table
CREATE TABLE public.projects (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name         VARCHAR(255) NOT NULL DEFAULT 'Untitled Project',
  canvas_data  JSONB,
  room_id      UUID DEFAULT gen_random_uuid(),  -- for live collaboration sharing
  created_at   TIMESTAMPTZ DEFAULT NOW(),
  updated_at   TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for fast lookups
CREATE INDEX IF NOT EXISTS idx_projects_user_id ON public.projects(user_id);
CREATE INDEX IF NOT EXISTS idx_projects_room_id ON public.projects(room_id);

-- Enable Row Level Security (RLS) on projects
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

-- Owner has full access to their projects
CREATE POLICY "owner_all" ON public.projects FOR ALL
  USING (auth.uid() = user_id);

-- Any authenticated user can read if they have access to the room
CREATE POLICY "collaborator_access" ON public.projects FOR SELECT
  USING (auth.role() = 'authenticated');

-- Any authenticated user can update if they have access to the room
CREATE POLICY "collaborator_update" ON public.projects FOR UPDATE
  USING (auth.role() = 'authenticated');

-- Create comments table
CREATE TABLE public.comments (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id   UUID NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  user_id      UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  canvas_x     FLOAT NOT NULL,
  canvas_y     FLOAT NOT NULL,
  content      TEXT NOT NULL,
  resolved     BOOLEAN DEFAULT FALSE,
  created_at   TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) on comments
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

-- Any authenticated user can interact with comments
CREATE POLICY "authenticated_access" ON public.comments FOR ALL
  USING (auth.role() = 'authenticated');

-- Setup auto-updating `updated_at` column function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Add updated_at trigger for projects
CREATE TRIGGER update_projects_updated_at
    BEFORE UPDATE ON public.projects
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
